In [3]:
import pandas as pd
import numpy as np

In [4]:
df1=pd.read_csv("train.csv")
df1.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
dfle=df1
cols=['LotFrontage','MSZoning','Street','Alley','LotShape','LandContour','Utilities','LotConfig','Neighborhood','LandSlope','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for col in cols:
    dfle[col]=le.fit_transform(dfle[col])
    dfle

In [7]:
dfle['LotFrontage']=dfle['LotFrontage'].fillna(dfle['LotFrontage'].median())

In [8]:
dfle['GarageYrBlt']=dfle['GarageYrBlt'].fillna(dfle['GarageYrBlt'].median())

In [9]:
dfle['MasVnrArea']=dfle['MasVnrArea'].fillna(dfle['MasVnrArea'].median())

In [10]:
X=dfle.drop(['SalePrice','Id'],axis='columns')
X

      MSSubClass  MSZoning  LotFrontage  ...  YrSold  SaleType  SaleCondition
0             60         3           36  ...    2008         8              4
1             20         3           51  ...    2007         8              4
2             60         3           39  ...    2008         8              4
3             70         3           31  ...    2006         8              0
4             60         3           55  ...    2008         8              4
...          ...       ...          ...  ...     ...       ...            ...
1455          60         3           33  ...    2007         8              4
1456          20         3           56  ...    2010         8              4
1457          70         3           37  ...    2010         8              4
1458          20         3           39  ...    2010         8              4
1459          20         3           46  ...    2008         8              4

[1460 rows x 79 columns]

In [11]:
y=dfle.SalePrice
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [14]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [15]:
model.fit(X_train,y_train)

LinearRegression()

In [16]:
dfle.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [17]:
null_counts=dfle.isnull().sum()
print(null_counts[null_counts>0])

Series([], dtype: int64)

In [18]:
model.predict(X_test)

array([115600.1857183 , 206912.43291591, 118901.75734687, 181842.43717074,
       105699.13069789, 200876.82284274, 229826.21604515, 143785.12621087,
       239101.94490612, 141442.42672926, 125734.5791613 ,  94797.17093991,
       214645.2253932 , 174864.37222198, 158177.59481079, 154622.41436463,
       117549.33853925, 179746.4817585 , 114712.45524324, 170510.24281973,
       123221.24941127, 158767.55763801, 188505.28602324, 120240.13211418,
       201422.10445322, 112102.09471666, 157864.88564661, 156246.81907049,
       308287.32780362, 187374.34349033, 118722.99092646, 281151.79386376,
       137943.42023889, 199716.57992932, 238635.81434995, 153674.74200631,
       187954.90003576, 224750.50702491,  92110.89316069, 232738.77297936,
       149430.94183077, 190007.82556386, 173183.94516915, 132239.37375716,
       126718.74810999, 199055.29089069,  68124.10420571, 168217.97151494,
       154859.36573198, 154484.93712173, 102308.3417716 , 252577.35139429,
       151922.24200637, 102770.62065103, 213013.03812053, 144307.90101225,
       232022.98582321, 157424.18098045,  80337.38258906, 273074.26185084,
       140456.25622746, 165736.40605441, 123123.54231103, 184813.20221038,
       221194.38864812, 217930.48830434, 134235.01975267, 300710.94990284,
       170132.99805691, 328396.89442167, 364958.37672058, 170075.26989352,
       107753.1211232 , 166172.42313364, 138888.4501686 , 106080.17583217,
       271946.3231841 , 297298.82420174, 179486.05172889, 262338.11923326,
       254653.79146594,  78688.59318305, 162201.02700908,  47049.83140505,
        94269.73880334, 159441.84762041, 112378.10545158, 188255.84225009,
       355396.39901574, 301805.31488833, 155084.17773055, 182981.86835188,
       191893.93842157, 196173.18842536, 132008.17469941, 218418.26959202,
       153861.99037241, 257036.49354172, 247190.19472702, 133039.17053556,
       115989.52728258, 138822.47862413, 188236.4282697 , 153924.00887159,
       228440.82220394, 253798.98617784, 153547.70881139, 199954.9758175 ,
       393256.90394014, 131172.34946512, 204384.12797971, 151120.98749073,
       250220.69857272, 133769.84834324, 135514.08552474, 299735.05177016,
       246912.34925601, 183033.6820862 , 221486.52312109, 219318.12650384,
       194147.36067961, 317336.73614937, 139409.89618212, 227270.57618392,
       267481.47252577, 176290.37657146,  78189.89589484, 107184.13272244,
       251323.80221423, 142757.57464168,  87078.64918381, 227157.92880967,
       126824.12983105, 260735.55585777, 115064.87879982, 191086.32896038,
        96215.35908208, 250269.68950262, 159822.82353207, 186534.15876095,
       124729.8187211 , 177272.76333644, 230654.88325056, 140477.25441176,
       112856.95871877, 149403.37058384, 254796.08061604, 294066.97205123,
       141912.3235158 , 174378.70852465, 134344.57472371, 131527.56494996,
        71107.85362703, 164472.98991367, 172295.55276217, 154767.95157432,
       180278.1322321 , 408470.96284409, 200024.79557772, 207664.35593397,
       250352.65893242, 287683.44536916, 108554.94967926,  85521.32109212,
       224474.65433455, 224251.55658066,  35143.00020256, 112708.82437511,
        61938.77970193, 220926.56024591, 133505.25899352, 216448.9674431 ,
       114281.62768971, 211478.83297865, 231455.50672996,  19806.36202359,
       189734.81448533, 127961.51510858, 148436.27659843, 190399.59926577,
       167759.96951264, 175515.30211492, 128477.59495556, 211286.45939336,
       200646.73367458, 285890.53931736, 147128.9753197 ,  77807.56585007,
       152568.4692262 , 324075.20578573, 172707.74924755, 138857.05491512,
        96318.08817154, 108796.85041937, 191759.13979319, 108479.33327757,
       177948.70841318, 317445.25008292, 193884.19104144, 188761.85618635,
       200544.16372235, 234501.44154457, 113634.82221195, 201279.48455168,
       123705.1636217 ,  81936.08845693, 107326.40753255, 194125.89397966,
       151796.37134328, 237544.29192333, 131601.04705039, 172496.45111167,
        90107.88439221, 263921.99746976, 245434.75675714, 150864.61383929,
       134205.11158416, 140518.7511213 , 177931.0754077 , 156516.65957455,
       110548.81966511, 240327.97113378,  97967.17049943, 138329.12867625,
       106174.77966163, 230391.46711666, 220712.77262287, 135313.46830485,
       124650.03966968, 194090.50720149, 133704.58960159, 155402.23660934,
       262273.74669272, 123363.54309918, 232115.71273797, 126884.93168884,
       573070.04331361, 162258.50153102, 119175.55840248, 210621.02989234,
       110150.10706254, 114578.29962892, 133919.16261883, 223475.89568697,
       168103.98971037, 177953.43823946, 224795.49027583,  74880.61735747,
       115603.54469559, 142893.63574936, 152350.52108011, 257600.16739505,
       231141.0457522 , 192027.06866761, 142204.84246377, 201796.87120471,
       224637.02334418, 153534.3856742 , 193965.65543686, 224375.9417354 ,
       110300.70357255, 110436.12955028, 154568.8961214 , 236554.37103355,
        83000.14243119, 192456.99960123, 271178.04661968, 151871.18121897,
       225529.13473848, 191832.00620433, 184579.43621452, 132192.42044049,
       220636.43355681, 210629.11082774, 161064.69060334, 137851.30239818,
       144736.01346947, 124041.55999366, 235734.81640197, 173734.78292895,
       227926.4055106 ,  58698.15578408, 150138.08709527, 118184.41725216,
       256034.12957902, 117738.031333  , 187064.67456886, 189068.61675413,
       140937.66323755, 107740.59915165, 145317.4867027 , 153134.46545436])

In [19]:
model.score(X_test,y_test)

0.7378977577051349

In [20]:
df2=pd.read_csv("test.csv")
df2.head()

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [22]:
dfle2=df2
cols=['LotFrontage','MSZoning','Street','Alley','LotShape','LandContour','Utilities','LotConfig','Neighborhood','LandSlope','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for col in cols:
    dfle2[col]=le.fit_transform(dfle2[col])
    dfle2

In [23]:
dfle2['LotFrontage']=dfle['LotFrontage'].fillna(dfle2['LotFrontage'].median())

In [24]:
dfle2['GarageYrBlt']=dfle['GarageYrBlt'].fillna(dfle2['GarageYrBlt'].median())

In [25]:
dfle2['MasVnrArea']=dfle['MasVnrArea'].fillna(dfle2['MasVnrArea'].median())

In [26]:
dfle2

        Id  MSSubClass  MSZoning  ...  YrSold  SaleType  SaleCondition
0     1461          20         2  ...    2010         8              4
1     1462          20         3  ...    2010         8              4
2     1463          60         3  ...    2010         8              4
3     1464          60         3  ...    2010         8              4
4     1465         120         3  ...    2010         8              4
...    ...         ...       ...  ...     ...       ...            ...
1454  2915         160         4  ...    2006         8              4
1455  2916         160         4  ...    2006         8              0
1456  2917          20         3  ...    2006         8              0
1457  2918          85         3  ...    2006         8              4
1458  2919          60         3  ...    2006         8              4

[1459 rows x 80 columns]

In [27]:
model.predict(X)

array([213013.03812053, 201422.10445322, 215522.73336645, ...,
       232022.98582321, 147299.16083397, 166094.57126367], shape=(1460,))

In [28]:
model.score(X,y)

0.8491057007366961

In [29]:
#sbse pehle import krna
import pandas as pd
df=pd.read_csv('test.csv')
#fir usko check krna k koi object(mtlb string) wala column to ni hai
df.info()
#agar koi string wala column hai to
from sklearn.preprocessing import LabelEncoder
str_cols = df.select_dtypes(include='object').columns
df[str_cols] = df[str_cols].apply(LabelEncoder().fit_transform)
# abb next null values se deal krna. Hum akele akele ke liye nahi lgayenge. Saare dataframe ke liye lgayenge
df.fillna(df.median(), inplace=True)
#now you data is clean

<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   str
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   str
 6   Alley          107 non-null    str
 7   LotShape       1459 non-null   str
 8   LandContour    1459 non-null   str
 9   Utilities      1457 non-null   str
 10  LotConfig      1459 non-null   str
 11  LandSlope      1459 non-null   str
 12  Neighborhood   1459 non-null   str
 13  Condition1     1459 non-null   str
 14  Condition2     1459 non-null   str
 15  BldgType       1459 non-null   str
 16  HouseStyle     1459 non-null   str
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   str
 22  RoofMatl       1459 non-null   str
 23  Exterior1st    1458 non-null   str
 24  Exterior2nd    1458 non-null   str
 25  MasVnrType     565 non-null    str
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   str
 28  ExterCond      1459 non-null   str
 29  Foundation     1459 non-null   str
 30  BsmtQual       1415 non-null   str
 31  BsmtCond       1414 non-null   str
 32  BsmtExposure   1415 non-null   str
 33  BsmtFinType1   1417 non-null   str
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   str
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   str
 40  HeatingQC      1459 non-null   str
 41  CentralAir     1459 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   str
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   str
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    str
 58  GarageType     1383 non-null   str
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   str
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   str
 64  GarageCond     1381 non-null   str
 65  PavedDrive     1459 non-null   str
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      str
 73  Fence          290 non-null    str
 74  MiscFeature    51 non-null     str
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   str
 79  SaleCondition  1459 non-null   str
dtypes: float64(11), int64(26), str(43)
memory usage: 912.0 KB

C:\Users\Prachi\AppData\Local\Temp\ipykernel_8260\3914820513.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include='object').columns

        Id  MSSubClass  MSZoning  ...  YrSold  SaleType  SaleCondition
0     1461          20         2  ...    2010         8              4
1     1462          20         3  ...    2010         8              4
2     1463          60         3  ...    2010         8              4
3     1464          60         3  ...    2010         8              4
4     1465         120         3  ...    2010         8              4
...    ...         ...       ...  ...     ...       ...            ...
1454  2915         160         4  ...    2006         8              4
1455  2916         160         4  ...    2006         8              0
1456  2917          20         3  ...    2006         8              0
1457  2918          85         3  ...    2006         8              4
1458  2919          60         3  ...    2006         8              4

[1459 rows x 80 columns]

In [30]:
model.predict(X)

array([213013.03812053, 201422.10445322, 215522.73336645, ...,
       232022.98582321, 147299.16083397, 166094.57126367], shape=(1460,))

In [32]:
model.score(X,y)

0.8491057007366961

In [33]:
import pandas as pd

# Make predictions
predictions = model.predict(X_test)

# Create DataFrame
submission = pd.DataFrame({
    'SalePrice': predictions,
  'Id': X_test['Id'],
})

# Save to CSV
submission.to_csv('submission.csv', index=False)

KeyError: 'Id'